spring:
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://database:5432/mordent
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://database:5432/mordent
  kafka:
    bootstrap-servers: broker:9092

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
