spring:
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mordent
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mordent
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
