server:
  port: 8082

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: bt769271@gmail.com
    password: hmcixzhniojxsatd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    consumer:
      topics:
        registration: mordent-registration-event
        activate: mordent-activate-event
        save-song: mordent-save-song-event
        listen-song: mordent-listen-song-event
        forgot-password: mordent-forgot-password-event
        reset-password: mordent-reset-password-event

logging.pattern.level: "%5p [${spring.application.name:} %X{traceId:-} %X{spanId:-}]"

application:
  host: https://mordent.local.com
