version: '3.8'
name: 'mordent'

services:
  auth-service:
    build: .
    #  context: .
    #  dockerfile: Prebuilt.Dockerfile
    container_name: auth-service
    ports:
      - '8080:8080'
    depends_on:
      - database
      - broker
      - zipkin
    links:
      - 'database:database'
      - 'broker:broker'
      - 'zipkin:zipkin'
    environment:
      SPRING_PROFILES_ACTIVE: localDocker
    networks:
      - mordent-network

  database:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mordent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mordent-database:/var/lib/postgresql/data
    networks:
      - mordent-network

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mordent-network

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mordent-network

  local-zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: local-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mordent-network
    profiles:
      - local

  local-broker:
    image: confluentinc/cp-kafka
    container_name: local-broker
    ports:
      - '9092:9092'
    depends_on:
      - local-zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'local-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - mordent-network
    profiles:
      - local

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - '9411:9411'
    networks:
      - mordent-network

#if "network mordent-network declared as external, but could not be found"
#start script "docker network create mordent-network"
networks:
  mordent-network:
    external: true
    driver: bridge
    name: mordent-network

volumes:
  #if "external volume "mordent-database" not found"
  #start script "docker volume create mordent-database"
  mordent-database:
    external: true
    name: mordent-database
