branches:
  - "main"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: "sed -i \"s/\"version\":.*/\"version\": \"${nextRelease.version}\",/g\" package.json"
  - "@semantic-release/gitlab"
  - - "@semantic-release/changelog"
    - assets:
        - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version.json
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/exec"
    - publishCmd: 'curl -X POST -F "token=$CI_JOB_TOKEN" -F "ref=v${nextRelease.version}" https://gitlab.com/api/v4/projects/${process.env.CI_PROJECT_ID}/trigger/pipeline'
